apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-claim1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: database-claim1
    namespace: default
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-database-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: sample-database-data
    namespace: default
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
